app = "foodapp-g2709a"
primary_region = "sin"

[build]
  context = "Backend"
  dockerfile = "Backend/Dockerfile"
  builder = "paack"

[env]
  NODE_ENV = "production"

[deploy]
  strategy = "rolling"
  max_unavailable = 1

[[services]]
  internal_port = 5001
  processes = ["app"]
  protocol = "tcp"
  
  [services.concurrency]
    type = "connections"
    hard_limit = 1024
    soft_limit = 1000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.tcp_checks]
    enabled = true
    grace_period = "10s"
    interval = "15s"
    timeout = "5s"

[autoscaling]
  min_machines = 1
  max_machines = 3
